import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Agents",
      items: [
        {
          type: "doc",
          id: "api/get-agent",
          label: "getAgent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/download-agent",
          label: "downloadAgent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-agents",
          label: "getAgents",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Connections",
      items: [
        {
          type: "doc",
          id: "api/get-connection",
          label: "getConnection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-connections",
          label: "getConnections",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      items: [
        {
          type: "doc",
          id: "api/get-file",
          label: "getFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-files",
          label: "getFiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/download-file",
          label: "downloadFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/upload-file",
          label: "uploadFile",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Flows",
      items: [
        {
          type: "doc",
          id: "api/get-flow",
          label: "getFlow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-flows",
          label: "getFlows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-flow-inputs",
          label: "getFlowInputs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/trigger-flow",
          label: "triggerFlow",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "FlowRuns",
      items: [
        {
          type: "doc",
          id: "api/get-flow-run",
          label: "getFlowRun",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-flow-runs",
          label: "getFlowRuns",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Tables",
      items: [
        {
          type: "doc",
          id: "api/get-table",
          label: "getTable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-tables",
          label: "getTables",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-query",
          label: "postQuery",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Hosts",
      items: [
        {
          type: "doc",
          id: "api/get-host",
          label: "getHost",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-hosts",
          label: "getHosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/download-gateway",
          label: "downloadGateway",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-connectors",
          label: "getConnectors",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/agentstate",
          label: "AgentState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/tag",
          label: "Tag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentversion",
          label: "AgentVersion",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agent",
          label: "Agent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectionstate",
          label: "ConnectionState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connection",
          label: "Connection",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/file",
          label: "File",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fileuploadbody",
          label: "FileUploadBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/flow",
          label: "Flow",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/flowinputschema",
          label: "FlowInputSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/flowinput",
          label: "FlowInput",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/triggerflowbody",
          label: "TriggerFlowBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/flowrunstate",
          label: "FlowRunState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/flowrun",
          label: "FlowRun",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/schemafield",
          label: "SchemaField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/table",
          label: "Table",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/postquerybody",
          label: "PostQueryBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/tablerow",
          label: "TableRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/hoststate",
          label: "HostState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/eventconfiguration",
          label: "EventConfiguration",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectortriggeroptions",
          label: "ConnectorTriggerOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/duplicatehandling",
          label: "DuplicateHandling",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cloudprovider",
          label: "CloudProvider",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/bucketowner",
          label: "BucketOwner",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/ingestbucket",
          label: "IngestBucket",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorfilewatcher",
          label: "ConnectorFileWatcher",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorcron",
          label: "ConnectorCron",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorcloudwatcher",
          label: "ConnectorCloudWatcher",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectoroneshot",
          label: "ConnectorOneShot",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectoractionoptions",
          label: "ConnectorActionOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorinputparametertype",
          label: "ConnectorInputParameterType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorinputparam",
          label: "ConnectorInputParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectortriggerflowparam",
          label: "ConnectorTriggerFlowParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectoruploadfile",
          label: "ConnectorUploadFile",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/configurableconnectorstypes",
          label: "ConfigurableConnectorsTypes",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/legacyfwflowconnectorconfig",
          label: "LegacyFWFlowConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/legacyfwuploadconnectorconfig",
          label: "LegacyFWUploadConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/legacycwsavefileconnectorconfig",
          label: "LegacyCWSaveFileConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fwflowconnectorconfig",
          label: "FWFlowConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fwuploadconnectorconfig",
          label: "FWUploadConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cronflowconnectorconfig",
          label: "CronFlowConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cronuploadconnectorconfig",
          label: "CronUploadConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cwsavefileconnectorconfig",
          label: "CWSaveFileConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/oneshotflowconnectorconfig",
          label: "OneShotFlowConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/oneshotuploadconnectorconfig",
          label: "OneShotUploadConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appstartupconnectorconfig",
          label: "AppStartupConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appcleanupconnectorconfig",
          label: "AppCleanupConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appcleanupflowconnectorconfig",
          label: "AppCleanupFlowConnectorConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/autofilepatternflowmappingconfig",
          label: "AutoFilePatternFlowMappingConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploadafterpause",
          label: "UploadAfterPause",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filetagtype",
          label: "FileTagType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/unappliedfiletag",
          label: "UnappliedFileTag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorstate",
          label: "ConnectorState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accesstype",
          label: "AccessType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/applicationsession",
          label: "ApplicationSession",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorhistoryentry",
          label: "ConnectorHistoryEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cronparam",
          label: "CronParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/globparam",
          label: "GlobParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filewatcherparam",
          label: "FileWatcherParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/inputparamtypeenum",
          label: "InputParamTypeEnum",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/inputparam",
          label: "InputParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/triggerflowparam",
          label: "TriggerFlowParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cloudwatcherparam",
          label: "CloudWatcherParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/actionoptions",
          label: "ActionOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/triggeroptions",
          label: "TriggerOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentstatev-4",
          label: "AgentStateV4",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/supportedconnectionoperatingsystems",
          label: "SupportedConnectionOperatingSystems",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/supportedconnectionmachinearchitectures",
          label: "SupportedConnectionMachineArchitectures",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/inferreddata",
          label: "InferredData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/secret",
          label: "Secret",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectionv-4",
          label: "ConnectionV4",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/generatedasset",
          label: "GeneratedAsset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/assetlist",
          label: "AssetList",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/buildeventclass",
          label: "BuildEventClass",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/historyentryv-4",
          label: "HistoryEntryV4",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentv-4",
          label: "AgentV4",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/supportedhostoperatingsystems",
          label: "SupportedHostOperatingSystems",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/supportedhostmachinearchitectures",
          label: "SupportedHostMachineArchitectures",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/hostinferreddata",
          label: "HostInferredData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/hostversionmetadata",
          label: "HostVersionMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/hoststatus",
          label: "HostStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/host",
          label: "Host",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/customimage",
          label: "CustomImage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connector",
          label: "Connector",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorconnectionstate",
          label: "ConnectorConnectionState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorconnectionstatus",
          label: "ConnectorConnectionStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connectorconnection",
          label: "ConnectorConnection",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
