name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.0
      name: Checkout
    - id: changed_files
      name: Changed Files
      uses: tj-actions/changed-files@v45
    - id: md_changed_files
      name: Spellcheck Markdown files
      run: |-
        files=''
        for f in ${{ steps.changed_files.outputs.all }}
        do
          ext="${f##*.}"
          if [ $ext = "md" || $ext = "mdx" ];
          then
            files="${f} ${files}"
          fi
        done

        echo "files=${files}" >> $GITHUB_ENV
    - uses: rojopolis/spellcheck-github-actions@0.41.0
      name: Spellcheck
      if: ${{ env.files }}
      with:
        source_files: ${{ env.files }}
        task_name: Markdown
